site_name: String Manipulation Docs

theme:
  name: "material"
  features:
    - content.code.copy

plugins:
  - mkdocstrings

nav:
  - String Manipulation Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md


